# Generated by Django 3.0 on 2022-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=90)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('staring', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artists', models.TextField(max_length=500)),
                ('sold', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
